name: the_dart_side_of_clis
description: A CLI used to present a talk about CLIs in Dart
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.2.0
  process_run: ^0.12.5+2
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1

executables:
  the_dart_side_of_clis:
