name: dependency_injection_example

packages:
  - packages/core/*
  - packages/micro_features/*
  - .

scripts:
  setup:
    exec: flutter pub get

  build_runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: 'build_runner'
