name: dependency_injection
description: An example project to demo a compile-time safe DI solution for multi-package projects
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  http: ^0.13.1
  http_client:
    path: ./packages/core/http_client
  intl: ^0.18.0
  tabbar:
    path: ./packages/micro_features/tabbar
  
dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  melos: ^3.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
