name: pull_request

on:
  pull_request:
    paths:
      - 'flutter_and_dart/the_dart_side_of_clis/**'

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: echo $github
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}


      - name: 📦 Install Dependencies
        run: |
          dart pub get

      - name: 🤖 Install CLI
        run: make install

      - name: 👀 Verify PR title formatting
        run: the_dart_side_of_clis semantic_linter -m 'fix example'
